### ISSUE TITLE
Set Playwright and Puppeteer to use `new` headless mode by default

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/BackstopJS#73]
Let's make the full change in source to use `new` headless mode as the default.

Test regressions, test fallbacks, and ensure support for `old` mode is supported when `new` becomes vendor standard.

## Notes

- https://github.com/garris/BackstopJS/issues/1525#issue-2052250247
- [The Chromium team was supposed to default to `new` by EOY 2023](https://developer.chrome.com/docs/chromium/new-headless#try_out_the_new_headless)
- there [are reports](https://github.com/microsoft/playwright/issues/21216#issuecomment-1446678795) that Playwright runs 40% **_slower_** with `new` headless

**Comment by dgrebb** [comment]
@garris let's discuss this - I see some evidence that `new` headless is actually slower.

It [appears](https://github.com/ckeditor/ckeditor5/issues/14063#issuecomment-1685773339) that one can pass `headless: old` as the mode, which apparently silences the deprecation warnings.

Maybe that's an option for now? The Chromium team says "we're going to make that the default later this year" back in January. So ¯\_(ツ)_/¯

I'll look into ways perf testing can be done.

**Comment by garris** [comment]
Few thoughts.
1) pretty sure this is exposed in `engineOptions` so risk of defaulting this to the "wrong" setting is fairly low.  
2) we should probably default this to `headless: new` but provide code snippet in docs for users who might hit an incompatibility.
3) backstop stashes time started and time completed and spits out duration into the CLI.  So testing for performance should be pretty easy.   You could run sanity test sequentially 20 times and grep for the timing value to get a cumulative average.
4) I'm open to other approaches.  Just sharing gut reactions.   Cheers.

**Comment by dgrebb** [comment]
Closed by https://github.com/garris/BackstopJS/pull/1535

Super happy I haven't caused any nightmares yet.
